In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

from ctext import *
setapikey("demo")


import bs4 as bs
import urllib.request
corp={}
for x in range(1, 10):
    sauce = urllib.request.urlopen('https://www.kanripo.org/text/KR2a0012/00%d#1a' % (x)).read()
    soup = bs.BeautifulSoup(sauce, 'lxml')

    corp[x] = ""
    for paragraph in soup.find_all('p'):
        corp[x]+=paragraph.text


frequency=[]
chapter_list=[]

for i in corp:
    match_count = {} 
    for match in re.finditer(r"飲酒", corp[i]):
        matched_text = match.group(0) 
        if not matched_text in match_count:
            match_count[matched_text] = 0 
        match_count[matched_text] = match_count[matched_text] + 1
    frequency.append(str(match_count.values()))
    chapter_list.append(int(i))


d = {'Chapter': chapter_list, 'Frequency': frequency}
df = pd.DataFrame(data=d)
df['Frequency'] = df['Frequency'].map(lambda x: x.lstrip('dict_values([').rstrip('])'))
df.index = np.arange(1, len(df)+1)
df.replace('', 0, inplace=True)
df['Frequency'] = df['Frequency'].astype(int)

df

   Chapter  Frequency
1        1          0
2        2          0
3        3          0
4        4          1
5        5          0
6        6          0
7        7          1
8        8          0
9        9          1

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

from ctext import *
setapikey("demo")


import bs4 as bs
import urllib.request
corp={}
for x in range(10, 31):
    sauce = urllib.request.urlopen('https://www.kanripo.org/text/KR2a0012/0%d#1a' % (x)).read()
    soup = bs.BeautifulSoup(sauce, 'lxml')

    corp[x] = ""
    for paragraph in soup.find_all('p'):
        corp[x]+=paragraph.text


frequency=[]
chapter_list=[]

for i in corp:
    match_count = {} 
    for match in re.finditer(r"飲酒", corp[i]):
        matched_text = match.group(0) 
        if not matched_text in match_count:
            match_count[matched_text] = 0 
        match_count[matched_text] = match_count[matched_text] + 1
    frequency.append(str(match_count.values()))
    chapter_list.append(int(i))


d = {'Chapter': chapter_list, 'Frequency': frequency}
df = pd.DataFrame(data=d)
df['Frequency'] = df['Frequency'].map(lambda x: x.lstrip('dict_values([').rstrip('])'))
df.index = np.arange(1, len(df)+1)
df.replace('', 0, inplace=True)
df['Frequency'] = df['Frequency'].astype(int)

df

    Chapter  Frequency
1        10          0
2        11          4
3        12          0
4        13          0
5        14          0
6        15          0
7        16          0
8        17          0
9        18          0
10       19          2
11       20          0
12       21          0
13       22          0
14       23          0
15       24          0
16       25          0
17       26          1
18       27          1
19       28          0
20       29          2
21       30          2