In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

from ctext import *
setapikey("demo")

text = {}
text[1] = gettextasstring("ctp:analects/xue-er")
text[2] = gettextasstring("ctp:analects/wei-zheng")
text[3] = gettextasstring("ctp:analects/ba-yi")
text[4] = gettextasstring("ctp:analects/li-ren")
text[5] = gettextasstring("ctp:analects/gong-ye-chang")
text[6] = gettextasstring("ctp:analects/yong-ye")
text[7] = gettextasstring("ctp:analects/shu-er")
text[8] = gettextasstring("ctp:analects/tai-bo")
text[9] = gettextasstring("ctp:analects/zi-han")
text[10] = gettextasstring("ctp:analects/xiang-dang")
text[11] = gettextasstring("ctp:analects/xian-jin")
text[12] = gettextasstring("ctp:analects/yan-yuan")
text[13] = gettextasstring("ctp:analects/zi-lu")
text[14] = gettextasstring("ctp:analects/xian-wen")
text[15] = gettextasstring("ctp:analects/wei-ling-gong")
text[16] = gettextasstring("ctp:analects/ji-shi")
text[17] = gettextasstring("ctp:analects/yang-huo")
text[18] = gettextasstring("ctp:analects/wei-zi")
text[19] = gettextasstring("ctp:analects/zi-zhang")
text[20] = gettextasstring("ctp:analects/yao-yue")


frequency=[]
chapter_list=[]

for i in text:
    match_count = {} 
    for match in re.finditer(r"子曰", text[i]):
        matched_text = match.group(0) 
        if not matched_text in match_count:
            match_count[matched_text] = 0 
        match_count[matched_text] = match_count[matched_text] + 1
    frequency.append(str(match_count.values()))
    chapter_list.append(int(i))


d = {'Chapter': chapter_list, 'Frequency': frequency}
df = pd.DataFrame(data=d)
df['Frequency'] = df['Frequency'].map(lambda x: x.lstrip('dict_values([').rstrip('])'))
df.index = np.arange(1, len(df)+1)
df.replace('', 0, inplace=True)
df['Frequency'] = df['Frequency'].astype(int)

df

    Chapter  Frequency
1         1         15
2         2         25
3         3         20
4         4         27
5         5         27
6         6         26
7         7         29
8         8         20
9         9         22
10       10          0
11       11         31
12       12         25
13       13         35
14       14         50
15       15         43
16       16         14
17       17         29
18       18          4
19       19          4
20       20          6